### PR TITLE
composer require phpactor/phpactor:^0.11

### PR DESCRIPTION
**Pull request by zonuexe**
https://github.com/phpactor/phpactor/releases/tag/0.10.0

### CODE REVIEW

**Comment by kermorgant** [comment]
Hello,

Just gave it a shot : 

- running 'phpactor-update' took a significant time (makes me think a note in the README about that might be worth it)

- restarted emacs and got this error in *Phpactor Output*

```
In Filesystem.php line 101:
                                                                               
  The "/home/mikael/src/phpactor.el/vendor/phpactor/phpactor/vendor/phpactor/  
  code-builder/templates" directory does not exist ("/home/mikael/src/phpacto  
  r.el/vendor/phpactor/phpactor/vendor/phpactor/code-builder/templates").      
```

**Comment by zonuexe** [comment]
refs https://github.com/emacs-php/phpactor.el/issues/80

**Comment by kermorgant** [comment]
@zonuexe as a sidenote :

I've started targeting develop branch for some pull requests to keep the freedom to experience a bit.

Could the develop branch be used for us as a staging phase for potentially disrupting changes, which I start to think this issue is

(I've been tempted to define the develop branch as the default one but as I was unsure about the scope of that change, I did not. Does that sound ok to make this switch ?)

**Comment by zonuexe** [comment]
@kermorgant 
I agree to implement the experimental feature with the development branch. 👍 
We can avoid destroying the environment of users who use MELPA instead of MELPA Stable.

**Comment by kermorgant** [comment]
@zonuexe thanks !

> My guess is that there's been a change in the RPC protocol, but I've asked @dantleech on slack to be sure.

My bad, the issue disapeared after restarting emacs... (`phpactor status` works)

But still, trying completion ended with this message 

```
{"version":"1.0.0","action":"error","parameters":{"message":"RecursiveDirectoryIterator::__construct(\/home\/mikael\/src\/phpactor.el\/vendor\/phpactor\/phpactor\/vendor\/jetbrains\/phpstorm-stubs): failed to open dir: No such file or directory","details":"0: RecursiveDirectoryIterator::__construct(\/home\/mikael\/src\/phpactor.el\/vendor\/phpactor\/phpactor\/vendor\/jetbrains\/phpstorm-stubs): failed to open dir: No such file or directory\n#0 \/home\/mikael\/src\/phpactor.el\/vendor\/phpactor\/worse-reflection\/lib\/Core\/SourceCodeLocator\/StubSourceLocator.php(87): RecursiveDirectoryIterator->__construct('\/home\/mikael\/sr...', 4096)\n#1 \/home\/mikael\/src\/phpactor.el\/vendor\/phpactor\/worse-reflection\/lib\/Core\/SourceCodeLocator\/StubSourceLocator.php(63): Phpactor\\WorseReflection\\Core\\SourceCodeLocator\\StubSourceLocator->fileIterator()\n#2 \/home\/mikael\/src\/phpactor.el\/vendor\/phpactor\/worse-reflection\/lib\/Core\/So....
```

`jetbrains` folder is to be found under vendor, not vendor/phpactor/vendor

**Comment by zonuexe** [comment]
I added `jetbrains/phpstorm-stubs`.

**Comment by kermorgant** [comment]
Thx !

Now facing this 

```

In RpcExtension.php line 52:
                                                                               
  Handler "extension_manager.rpc.handler.list" must be provided with a "name"  
   attribute when it is registered                                             
                                                                               

```

**Comment by kermorgant** [comment]
Just talked with @dantleech on slack

1- this error might need another tag for the extension-manager dependency
2- we probably should only require phpactor/phpactor which means we should find another way (than adding the dependencies ourself) to solve the path issues I referenced earlier

**Comment by kermorgant** [comment]
@dantleech I tried and it worked. Is that an acceptable solution for a PR ?

**Comment by dantleech** [comment]
Yeah sure

**Comment by kermorgant** [comment]
Hi @zonuexe 

You can revert to only requiring phpactor/phpactor (should be fixed whe [this PR](https://github.com/phpactor/phpactor/pull/668) is merged)

**Comment by kermorgant** [comment]
@zonuexe you ca now target version 0.11.1 (thanks @dantleech ) which includes the path fix mentioned above.

**Comment by kermorgant** [comment]
@zonuexe I realized I had access to the branch so I pushed the change. OK for you ?

**Comment by kermorgant** [comment]
No worry.
I solved that installation issue by doing `composer install --no-dev --ignore-platform-reqs`.

I understood the issue was related to a development dependency (php-cs-fixer I remember), which would anyway cause `composer install --no-dev` to fail. Thus, I think the error can be ignored (except the installation needs the ignore-platform-reqs, which I think should be done manually for the time being, no ?)

**Comment by zonuexe** [comment]
@kermorgant 
It seems like the problem I saw.  I would like to merge this change.

**Comment by kermorgant** [comment]
Ok for me !

Le ven. 4 janv. 2019 à 15:00, USAMI Kenta <notifications@github.com> a
écrit :

**Pull request merged**
