### PR TITLE
Fix regression from pr #29 causing completion on object to fail

### PR DESCRIPTION
**Pull request by kermorgant**
Sorry for last PR, it introduced a regression when completion occured on object methods...

This should hopefully fix that

### CODE REVIEW

**Comment by ejmr** [comment]
Thank you for catching the regression and correcting it.  In my experience those things exist for *way* too long in too many open-source projects.

**Comment by kermorgant** [comment]
I've been using thix fix for some days now and I haven't observed any problem.

@zonuexe I'm tempted to merge this one as I can only see benefits with it. would you be ok for a merge ?

**Comment by kermorgant** [comment]
As a side note, I've noticed [a pull request(https://github.com/emacs-php/php-mode/pull/409) which might be worth to follow in regard to how completion works with company-phpactor.

I've not checked personnally how it would change things, but I thought adding this comment might be useful in the future.

**Comment by kermorgant** [comment]
@ejmr are you suggesting to open a pull request directly for php-mode ?

**Comment by ejmr** [comment]
@kermorgant 

> ...are you suggesting to open a pull request directly for php-mode?

No.  I accidentally typed the wrong project name.  Hilariously in a comment where I called *you* out on a typo, lol.  I meant this change should be merged in `phpactor.el`.

**Comment by zonuexe** [comment]
@kermorgant LGTM

> @zonuexe I'm tempted to merge this one as I can only see benefits with it. would you be ok for a merge?

You can merge such trivial bugs at your discretion. 👍

**Comment by zonuexe** [comment]
BTW, I had a serious problem in managing the issue / PR's reading and resolution, but I installed [Jasper app](https://jasperapp.io/) today.  I am trying to improve my response by that.

**Pull request merged**
